"use client"

import "./globals.css";
import emailjs from "@emailjs/browser";
import {NextIntlClientProvider} from "next-intl";
import Header from "@/app/component/header/Header";
import Footer from "@/app/component/footer/Footer";
import Head from "@/app/[locale]/head";


export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'uk'}, {locale: 'ru'}];
}

// export const metadata = {
//     title: 'Samwash',
//     description: 'Generated by create next app',
// }

export default async function RootLayout(props) {

    let messages;
    try {
        messages = (await import(`../../messages/${props?.params?.locale}.json`)).default
    } catch (error) {
        console.log()
    }

    setTimeout(() => {
        emailjs.init("938710462a5c1bb2ad85688812ab3da4")
    }, 8000)


    return (
        <html lang={props?.params.locale}>
        <NextIntlClientProvider locale={props?.params?.locale} messages={messages}>
            {/*<Provider store={store}>*/}
            <head>
                <Head/>
            </head>
            <body>
            <noscript>
                <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-NSRQJ7H" loading='eager'
                        title="facebook"
                        height="0" width="0" style={{display: 'none', visibility: 'hidden'}}></iframe>
            </noscript>
            <Header/>
            <main>
                {props?.children}
            </main>
            <Footer/>
            </body>
            {/*</Provider>*/}
        </NextIntlClientProvider>
        </html>
    )
}
